PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ex: <http://ex.org/a#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbf: <http://fr.dbpedia.org/resource/>
PREFIX db: <http://dbpedia.org/resource/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX swpo: <http://sw-portal.deri.org/ontologies/swportal#>

CONSTRUCT {
  ?URI a dbo:Event;
    foaf:name ?Dispositif;
    dbo:status ?Etat;
    swpo:hasLocation ?URI_Etab;
    foaf:Person [foaf:name ?Contact;
				foaf:name ?Contact2;
				foaf:email ?Email;
				foaf:email ?AutreEmail;
				foaf:website ?Site;
				foaf:role ?Role].
	
  ?URI_Etab rdf:type dbo:EducationalInstitution ;
    foaf:name ?NomEtab;
    swpo:hasLocation [	db:City ?URI_Ville;
						dbf:Departement ?URI_Departement;
						dbf:Region ?URI_Region ].
  
  ?URI_Ville a db:City;
	foaf:name ?Ville.

  ?URI_Departement a dbf:Departement;
	foaf:name ?Departement.
	
  ?URI_Region a dbf:Region;
	foaf:name ?Region.
}
FROM <fr-esr-initiatives-pour-la-lutte-contre-les-violences-sexistes-et-sexuelles_bis.csv>
WHERE {
  BIND (URI(?UAI) AS ?URI)
  BIND (URI(CONCAT("http://fr.dbpedia.org/resource/", REPLACE(?NomEtab, ' ', '_'))) AS ?URI_Etab)
  BIND (URI(CONCAT("http://dbpedia.org/resource/", REPLACE(?Ville, ' ', '_'))) AS ?URI_Ville)
  BIND (URI(CONCAT("http://fr.dbpedia.org/resource/", REPLACE(?Departement, ' ', '_'))) AS ?URI_Departement)
  BIND (URI(CONCAT("http://fr.dbpedia.org/resource/", REPLACE(?Region, ' ', '_'))) AS ?URI_Region)
}
