PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ex: <http://ex.org/a#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbf: <http://fr.dbpedia.org/resource/>
PREFIX db: <http://dbpedia.org/resource/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX swpo: <http://sw-portal.deri.org/ontologies/swportal#>

CONSTRUCT {
  ?URI a dbo:Event;
    foaf:name ?Dispositif;
    dbo:status ?Etat;
    swpo:hasLocation [ 
				rdf:type dbo:EducationalInstitution ;
				foaf:name ?NomEtab;
				swpo:hasLocation [ db:City ?VilleCC;
									dbf:Departement ?Departement;
									dbf:Region ?Region
								]
				];
    foaf:Person [foaf:name ?Contact;
				foaf:name ?Contact2;
				foaf:email ?Email;
				foaf:email ?AutreEmail;
				foaf:website ?Site;
				foaf:role ?Role].
}
FROM <fr-esr-initiatives-pour-la-lutte-contre-les-violences-sexistes-et-sexuelles_bis.csv>
WHERE {
  BIND (URI(?UAI) AS ?URI)
  BIND (xsd:string(?Ville) AS ?VilleCC)
}
